// =============================================================================
// ExposomeSim — NETGRAPH: the one true street graph.
// -----------------------------------------------------------------------------
// Built deterministically from the world's anchors (the five PLACES, off-core
// POIs, build lots). Streets are the classic seven place-pairs; every other
// anchor grows a spur to the nearest already-connected anchor, so the network
// is always one component. Where two street segments properly cross, an
// INTERSECTION node is generated by exact segment-intersection math and both
// segments are split there — those crossings are where the signal controllers
// live. The render draws exactly this graph (the duplicated STREETS literals
// die), so the generator is shaped for looks as much as for routing: straight
// segments, real crossings, sidewalk flags on the walkable core.
//
// Pure data + math: no RNG, no clock, allocation only at construction. The
// graph is a deterministic function of its anchors — it is NOT serialized;
// the facade re-derives it from the anchor list it was built with.
// =============================================================================

import type { ModeId, NetAnchor, NetEdge, NetNode, XZ } from './types';

/** the classic seven streets over the core places (citystage.ts STREETS). */
const CLASSIC_PAIRS: [string, string][] = [
  ['home', 'work'], ['home', 'market'], ['work', 'market'],
  ['market', 'thirdplace'], ['work', 'thirdplace'], ['home', 'park'], ['market', 'park'],
];

/** edges whose BOTH endpoints sit inside this radius of the origin get
 *  sidewalks (the walkable core); longer arterials out to the POIs do not. */
const SIDEWALK_CORE_FRAC = 0.9;

const ALL_MODES: ModeId[] = ['walk', 'bike', 'car', 'taxi', 'bus'];
const EPS_T = 1e-6;     // parametric tolerance: endpoint touches are not crossings
const MERGE_M = 0.05;   // coincident-crossing merge radius, metres

interface Seg { a: number; b: number; cuts: { t: number; node: number }[] }

export class StreetGraph {
  readonly nodes: NetNode[] = [];
  readonly edges: NetEdge[] = [];
  private byId = new Map<string, number>();
  private adj: number[][] = [];

  constructor(anchors: readonly NetAnchor[]) {
    // ---- nodes: every anchor, in caller order (deterministic) ---------------
    for (const a of anchors) this.pushNode({ id: a.id, x: a.x, z: a.z, kind: 'anchor', anchorKind: a.kind });

    // ---- segments: classic pairs, then spurs until one component ------------
    const segs: Seg[] = [];
    const touched = new Set<number>();
    for (const [pa, pb] of CLASSIC_PAIRS) {
      const ia = this.byId.get(pa), ib = this.byId.get(pb);
      if (ia === undefined || ib === undefined) continue;
      segs.push({ a: ia, b: ib, cuts: [] });
      touched.add(ia); touched.add(ib);
    }
    if (touched.size === 0 && anchors.length >= 2) {
      // no classic anchors at all (synthetic set): seed with anchor 0 → nearest.
      const j = this.nearestOther(0);
      segs.push({ a: 0, b: j, cuts: [] });
      touched.add(0); touched.add(j);
    }
    for (let i = 0; i < anchors.length; i++) {
      if (touched.has(i)) continue;
      // spur to the nearest connected anchor — the network stays one tree+core.
      let best = -1, bd = Infinity;
      for (const j of touched) {
        const d = this.d2(i, j);
        if (d < bd) { bd = d; best = j; }
      }
      if (best >= 0) { segs.push({ a: i, b: best, cuts: [] }); touched.add(i); }
    }

    // ---- intersections: exact pairwise segment crossings ---------------------
    let xn = 0;
    for (let i = 0; i < segs.length; i++) {
      for (let j = i + 1; j < segs.length; j++) {
        const s = segs[i], u = segs[j];
        if (s.a === u.a || s.a === u.b || s.b === u.a || s.b === u.b) continue; // shared endpoint
        const hit = segCross(this.p(s.a), this.p(s.b), this.p(u.a), this.p(u.b));
        if (!hit) continue;
        // merge with an existing crossing node if two crossings coincide.
        let ni = this.findNear(hit.x, hit.z, MERGE_M);
        if (ni < 0) ni = this.pushNode({ id: `x${xn++}`, x: hit.x, z: hit.z, kind: 'intersection' });
        s.cuts.push({ t: hit.t, node: ni });
        u.cuts.push({ t: hit.u, node: ni });
      }
    }

    // ---- edges: split each segment at its cuts, sorted along it -------------
    const coreR = SIDEWALK_CORE_FRAC * this.coreRadius(anchors);
    let en = 0;
    for (const s of segs) {
      s.cuts.sort((p, q) => p.t - q.t);
      let prev = s.a;
      for (const c of s.cuts) {
        if (c.node !== prev) this.pushEdge(`e${en++}`, prev, c.node, coreR);
        prev = c.node;
      }
      if (prev !== s.b) this.pushEdge(`e${en++}`, prev, s.b, coreR);
    }
  }

  // ---- queries ----------------------------------------------------------------

  idx(id: string): number { return this.byId.get(id) ?? -1; }

  /** edge indices incident to a node (live array — do not mutate). */
  edgesAt(nodeIdx: number): readonly number[] { return this.adj[nodeIdx] ?? []; }

  /** nearest node index to a world point — O(nodes), and nodes are ~tens. */
  nearestNode(x: number, z: number): number {
    let best = 0, bd = Infinity;
    for (let i = 0; i < this.nodes.length; i++) {
      const dx = this.nodes[i].x - x, dz = this.nodes[i].z - z;
      const d = dx * dx + dz * dz;
      if (d < bd) { bd = d; best = i; }
    }
    return best;
  }

  /** signal candidates: generated crossings + any node of degree ≥ 3. */
  intersections(): number[] {
    const out: number[] = [];
    for (let i = 0; i < this.nodes.length; i++) {
      if (this.nodes[i].kind === 'intersection' || (this.adj[i]?.length ?? 0) >= 3) out.push(i);
    }
    return out;
  }

  /** anchor-node indices — these are the transit STOPS. */
  anchorNodes(): number[] {
    const out: number[] = [];
    for (let i = 0; i < this.nodes.length; i++) if (this.nodes[i].kind === 'anchor') out.push(i);
    return out;
  }

  otherEnd(e: NetEdge, nodeIdx: number): number { return e.ai === nodeIdx ? e.bi : e.ai; }

  // ---- construction helpers -----------------------------------------------------

  private p(i: number): XZ { return this.nodes[i]; }

  private d2(i: number, j: number): number {
    const dx = this.nodes[i].x - this.nodes[j].x, dz = this.nodes[i].z - this.nodes[j].z;
    return dx * dx + dz * dz;
  }

  private nearestOther(i: number): number {
    let best = i === 0 ? 1 : 0, bd = Infinity;
    for (let j = 0; j < this.nodes.length; j++) {
      if (j === i) continue;
      const d = this.d2(i, j);
      if (d < bd) { bd = d; best = j; }
    }
    return best;
  }

  private findNear(x: number, z: number, r: number): number {
    for (let i = 0; i < this.nodes.length; i++) {
      const dx = this.nodes[i].x - x, dz = this.nodes[i].z - z;
      if (dx * dx + dz * dz <= r * r) return i;
    }
    return -1;
  }

  private pushNode(n: NetNode): number {
    this.byId.set(n.id, this.nodes.length);
    this.nodes.push(n);
    this.adj.push([]);
    return this.nodes.length - 1;
  }

  private pushEdge(id: string, ai: number, bi: number, coreR: number): void {
    const a = this.nodes[ai], b = this.nodes[bi];
    const len = Math.hypot(a.x - b.x, a.z - b.z);
    if (len < 1e-6) return;
    const inCore = Math.hypot(a.x, a.z) <= coreR && Math.hypot(b.x, b.z) <= coreR;
    const e: NetEdge = { id, a: a.id, b: b.id, ai, bi, lengthM: len, sidewalk: inCore, modes: ALL_MODES };
    this.adj[ai].push(this.edges.length);
    this.adj[bi].push(this.edges.length);
    this.edges.push(e);
  }

  /** the core scale — largest classic-anchor distance from origin, falling back
   *  to the median anchor radius for fully synthetic sets. */
  private coreRadius(anchors: readonly NetAnchor[]): number {
    let core = 0;
    for (const [pa, pb] of CLASSIC_PAIRS) {
      for (const id of [pa, pb]) {
        const i = this.byId.get(id);
        if (i !== undefined) core = Math.max(core, Math.hypot(this.nodes[i].x, this.nodes[i].z));
      }
    }
    if (core > 0) return core * 1.35;
    const rs = anchors.map((a) => Math.hypot(a.x, a.z)).sort((p, q) => p - q);
    return rs.length ? rs[rs.length >> 1] * 1.35 : 100;
  }
}

// ---- exact segment intersection ------------------------------------------------

/** proper interior crossing of segments p1p2 × p3p4 — parametric cross-product
 *  solve; endpoint touches and parallels return null. */
function segCross(p1: XZ, p2: XZ, p3: XZ, p4: XZ): { x: number; z: number; t: number; u: number } | null {
  const rx = p2.x - p1.x, rz = p2.z - p1.z;
  const sx = p4.x - p3.x, sz = p4.z - p3.z;
  const denom = rx * sz - rz * sx;
  if (Math.abs(denom) < 1e-12) return null;
  const qx = p3.x - p1.x, qz = p3.z - p1.z;
  const t = (qx * sz - qz * sx) / denom;
  const u = (qx * rz - qz * rx) / denom;
  if (t <= EPS_T || t >= 1 - EPS_T || u <= EPS_T || u >= 1 - EPS_T) return null;
  return { x: p1.x + t * rx, z: p1.z + t * rz, t, u };
}
